# Encoder
Encoders:
  cnn:
    type: CNMPImageEncoder
    data: images
    args:
      dim_lat: 128
      hidden_layers_obs:
        - 128
        - 128

      act_func: leaky_relu
      seed: 1234

# Aggregator
Aggregator:
  type: CNMPAggregator
  args:
    dim_lat: 128
    multiple_steps: true
    scalar_prior: True
    prior_mean: 0.0
  agg_order:
    default: [ ]

    extra:
      - cnn

# Decoder
Decoder:
  type: CNPDecoder
  args:
    dim_time: 1
    dim_val: 2
    dim_val_cov: 2
    dim_lat: 128
    std_only: True
    hidden_layers_mean_val:
      - 128
      - 128
      - 128
    hidden_layers_cov_val:
      - 128
      - 128
      - 128
      - 256
    act_func: leaky_relu
    seed: 1234


# Dataset
dataset:
  name: s_mnist_25/40x40-smnist.npz
  type: Mnist
  partition:
    train: 0.7
    validate: 0.15
    test: 0.15
  time: t
  data:
    images:
      num_points: 1
      dim_data:
        - 1
        - 40
        - 40
      load_func: null
      time_dependent: false
      context: true
      predict: false
      traj: false
    trajs:
      num_points: 301
      dim_data:
        - 2
      load_func: null
      time_dependent: true
      context: false
      predict: true
      traj: true
    outputs:
      num_points: 1
      dim_data:
        - 54
      load_func: null
      time_dependent: false
      context: false
      predict: false
      traj: false

# DataLoader
data_loader:
  batch_size: 512
  shuffle: true
  num_workers: 0

# Logger
logger:
  activate: True
  log_name: CNMP_MNIST
  type: wandb
  watch: false
  training_log_interval: 10
  save_model_interval: 100

# Loss
loss_func:
  type: nll_loss
  args:
    num_mc_smp: null

# Data Assignment Manager
data_assignment_manager:
  type: CNMPImageAssignment
  args:
    shuffle: True
#    ctx_dist: exponential
#    num_ctx_min: 0
#    num_ctx_max: 20

# Training
train_params:
  lr: 2e-4
  wd: 5e-5
  normalize: true
  seed: 1234
  validation_interval: 20
  len_loss_deque: 10
