# Encoder
Encoders:
  ctx:
    type: NMPEncoder
    data: ctx
    args:
      dim_time: 0
      dim_val: 4
      dim_lat: 128
      hidden_layers_obs:
        - 64
        - 64
        - 64
      hidden_layers_unc_obs:
        - 64
        - 64
        - 64
      act_func: leaky_relu
      seed: 1234

# Aggregator
Aggregator:
  type: NMPAggregator
  args:
    dim_lat: 128
    multiple_steps: true
    scalar_prior: True
    prior_mean: 0.0
    prior_var: 1
  agg_order:
    default: [ ]

    extra:
      - ctx


# Decoder
Decoder:
  type: PBDecoder
  args:
    dim_time: 0
    dim_val: 56 # 56 for 7idmp and 112 for 15idmp
    dim_lat: 128
    std_only: False
    hidden_layers_mean_val:
      - 64
      - 64
      - 64
    hidden_layers_cov_val:
      - 128
      - 256  # 128
      - 512  # 128
    act_func: leaky_relu
    seed: 1234


# Dataset
dataset:
  name: panda_pap_100_7_idmp # panda_pap_100_7_idmp for 7idmp and panda_pap_100_15_idmp for 15 idmp
  partition:
    train: 0.64  # 80
    validate: 0.20   # 25
    test: 0.16   # 20
  time: t
  data:
    ctx:
      num_points: 1
      dim_data:
        - 4
      load_func: null
      time_dependent: false
      context: true
      predict: false
      traj: false
    j_pos_vel:
      num_points: 101 # for 5s
      dim_data:
        - 14
      load_func: null
      time_dependent: true
      context: false
      predict: false
      traj: true
    idmp:
      num_points: 1
      dim_data:
        - 56 # 56 for 7idmp and 112 for 15idmp
      load_func: null
      time_dependent: false
      context: false
      predict: true
      traj: false
    corresponding_index:
      num_points: 1
      dim_data:
        - 1
      load_func: null
      time_dependent: false
      context: false
      predict: false
      traj: false
    corresponding_num:
      num_points: 1
      dim_data:
        - 1
      load_func: null
      time_dependent: false
      context: false
      predict: false
      traj: false

# DataLoader
data_loader:
  batch_size: 80
  shuffle: true
  num_workers: 0

# Logger
logger:
  activate: True
  log_name: NMP_IDMP_PANDA_PAP
  type: wandb
  watch: false
  training_log_interval: 50
  save_model_interval: 1000 # have to change to 2000 when using --

loss_func:
  type: mp_rec_ll_loss
#  type: mp_rec_mse_loss
  args:
    num_mc_smp: null
    mp_config: IDMP_Panda_PAP_config

# Data Assignment Manager
data_assignment_manager:
  type: PAPPairedAssignment
  args:
    num_pred_pts: 20

# Training
train_params:
  lr: 1e-4
  wd: 5e-5
  normalize: true
  seed: 1234
  validation_interval: 100
  len_loss_deque: 5