# Dataset
dataset: smnist
save_as_dataset: s_mnist_idmp_20
overwrite: true
num_dof: 2
time_key: t
data_keys:
  - x
  - y

mp_key: idmp

# MP
mp:
  type: idmp
  args:
    num_basis: 20
    basis_bandwidth_factor: 2
    num_basis_outside: 0
    alpha: 25
    duration: 3.0
    tau: 3.0
    alpha_phase: 2
    num_pc_times: 301
    pc_time_start: 0
    pc_time_stop: 3.0
    dt: 0.01