# Dataset
dataset: panda_pap_100
save_as_dataset: panda_pap_100_7_idmp  # panda_pap_100_7_idmp for 7idmp and panda_pap_100_15_idmp for 15 idmp
overwrite: true
num_dof: 7
time_key: t
data_keys:
  - j_pos_0
  - j_pos_1
  - j_pos_2
  - j_pos_3
  - j_pos_4
  - j_pos_5
  - j_pos_6
mp_key: idmp

# MP
mp:
  type: idmp
  args:
    num_basis: 7 # 7 for 7idmp and 15 for 15idmp
    basis_bandwidth_factor: 3
    num_basis_outside: 0
    alpha: 25
    tau: 5
    duration: 5
    alpha_phase: 3
    num_pc_times: 101
    pc_time_start: 0
    pc_time_stop: 5
    dt: 0.05