# Dataset
dataset: panda_rrp_compound
save_as_dataset: panda_rrp_idmp
overwrite: true
num_dof: 7
time_key: t
data_keys:
  - j_pos_0
  - j_pos_1
  - j_pos_2
  - j_pos_3
  - j_pos_4
  - j_pos_5
  - j_pos_6
#  - c_pos_0
#  - c_pos_1
mp_key: idmp

# MP
mp:
  type: idmp
  args:
    num_basis: 7
    basis_bandwidth_factor: 2
    num_basis_outside: 1
    alpha: 25
    tau: 0.299
    duration: 0.299
    alpha_phase: 3
    num_pc_times: 300
    pc_time_start: 0
    pc_time_stop: 0.299
    dt: 0.001