# Dataset
dataset: pap_100
save_as_dataset: pap_100_idmp
overwrite: true
num_dof: 1
time_key: t
data_keys:
#  - c_pos_1
  - c_pos_2

mp_key: idmp

# MP
mp:
  type: idmp
  args:
    num_basis: 10
    basis_bandwidth_factor: 3
    num_basis_outside: 0
    alpha: 25
    tau: 5 # 1.0
    duration: 5 # 1.0
    alpha_phase: 3
    num_pc_times: 101 # 101
    pc_time_start: 0
    pc_time_stop: 5 # 1.0
    dt: 0.05 # 0.01